/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jyotimaven;

import com.google.auth.oauth2.GoogleCredentials;
import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseAuthException;
import com.google.firebase.auth.UserRecord;
import com.google.firebase.auth.UserRecord.CreateRequest;
import java.util.Scanner;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Biswajit Roy
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    FirebaseAuth mAuth;
    FileInputStream serviceAccount;
    public register() {
        initComponents();
        try{
        Scanner sc=new Scanner(new File("LICENSE"));
        String fileData="";
        while(sc.hasNext()){
            fileData += sc.next()+" ";
        }
        license.setText(fileData);
        
//        serviceAccount = new FileInputStream("keys\\jyotiserver-firebase-adminsdk-y3tdf-2053ffefdd.json");
//            FirebaseOptions options = new FirebaseOptions.Builder()
//                .setCredentials(GoogleCredentials.fromStream(serviceAccount))
//                .setDatabaseUrl("https://jyotiserver.firebaseio.com")
//                .build();
//
//            FirebaseApp.initializeApp(options);
         
        }catch(FileNotFoundException ex){
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "License File Not Found Exception");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        fnameTF = new javax.swing.JTextField();
        lnameTF = new javax.swing.JTextField();
        unameTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        info = new javax.swing.JLabel();
        agreement = new java.awt.Checkbox();
        register = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        license = new javax.swing.JTextArea();
        authenticateL = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        phoneinfo = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jyoti - Registration Daemon");

        title.setFont(new java.awt.Font("HP Simplified Light", 0, 18)); // NOI18N
        title.setText("Jyoti - Registration Prompt");

        fnameLabel.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        fnameLabel.setText("First name:");

        lnameLabel.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        lnameLabel.setText("Last name:");

        usernameLabel.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        usernameLabel.setText("E-mail ID:");

        PhoneLabel.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        PhoneLabel.setText("Phone:");

        fnameTF.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N

        lnameTF.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N

        unameTF.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N

        passwordTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        info.setText("Terms and Conditions of usage");

        agreement.setLabel("I have read and understood the license and terms of usage");

        register.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        license.setEditable(false);
        license.setColumns(20);
        license.setLineWrap(true);
        license.setRows(5);
        license.setToolTipText("License Agreement and Terms of Usage");
        license.setBorder(javax.swing.BorderFactory.createTitledBorder("License Agreement"));
        license.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(license);

        authenticateL.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N

        PasswordLabel.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N
        PasswordLabel.setText("Password:");

        phoneTF.setFont(new java.awt.Font("HP Simplified Light", 0, 14)); // NOI18N

        phoneinfo.setText("( Please include country code )");

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agreement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(authenticateL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(476, 476, 476)
                .addComponent(phoneinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lnameLabel)
                            .addComponent(PhoneLabel))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fnameLabel)
                            .addComponent(usernameLabel)
                            .addComponent(PasswordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(backbtn)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtn)
                    .addComponent(title))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameLabel)
                    .addComponent(fnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameLabel)
                    .addComponent(lnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(unameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneinfo)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordLabel)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(info)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(agreement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(register)
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addComponent(authenticateL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        try {
            authenticateL.setText("Please wait. Authenticating...");
                        
            //Firebase Auth Register user...
            
            final String sender_email = unameTF.getText();

                if(fnameTF.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"Please enter your first name");
                    return;
                }
                
                else if(lnameTF.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"Please enter your last name");
                    return;
                }

                else if(unameTF.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"Please enter your E-mail ID");
                    return;
                }
                
                else if(agreement.getState() != true){
                    JOptionPane.showMessageDialog(null,"Please accept the agreement");
                    return;
                }
                
                else{
                    authenticateL.setText("Just a moment...");
                }

                mAuth = FirebaseAuth.getInstance();
                
                System.out.println("Firebase Auth response " + mAuth);
                
                
                CreateRequest request = new CreateRequest()
                    .setEmail(sender_email)
                    .setEmailVerified(false)
                    .setPassword(passwordTF.getPassword().toString())
                    .setPhoneNumber("+"+phoneTF.getText())
                    .setDisplayName(fnameTF.getText() + " " + lnameTF.getText())
                    .setPhotoUrl("https://avatars2.githubusercontent.com/u/26689027?s=400&u=18222d868827c0f26205a58b8f4360787a5b9382&v=4")
                    .setDisabled(false);
                UserRecord userRecord = mAuth.createUser(request);
                authenticateL.setText("Successfully registered.");
                JOptionPane.showMessageDialog(null,"Account Created Successfully");
                dispose();
                new dashboard().setVisible(true);
        } catch (FirebaseAuthException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
            authenticateL.setText("<html>Uh, Oh ! We ran into a problem.<br>We have dispatched a team of talented monkeys.<br>If you find them, just show this dialog to scare them.<p color=red>'Level = " + Level.SEVERE + "'</p></html>");
        } catch(Exception ex){
            authenticateL.setText("<html>Uh, Oh ! We ran into a problem.<br>We have dispatched a team of talented monkeys.<br>If you find them, just show this dialog to scare them.<p color=red>'Level = " + Level.SEVERE + "'</p></html>");
        }
        
    }//GEN-LAST:event_registerActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PhoneLabel;
    private java.awt.Checkbox agreement;
    private javax.swing.JLabel authenticateL;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField fnameTF;
    private javax.swing.JLabel info;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea license;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField lnameTF;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JLabel phoneinfo;
    private javax.swing.JButton register;
    private javax.swing.JLabel title;
    private javax.swing.JTextField unameTF;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
